[build]
  base = "frontend"
  command = "npm install && STATIC_EXPORT=true npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_API_URL = "https://spotify-mood-classification.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 