services:
  - type: web
    name: spotify-mood-backend
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "cd backend && python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.11
      - key: SPOTIFY_CLIENT_ID
        value: 9b3ef90111ac4a9797a5b9c14443e202
      - key: SPOTIFY_CLIENT_SECRET
        value: 962da8a54b7d48b09a775b156c2f9e30
      - key: GENIUS_ACCESS_TOKEN
        value: mrWS-HJtMGOPkVNLCjVNrNvu5bo1kUGPd9jxdIJHqtqgJPgflUId4s8b7PRbWUMN
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: spotify-mood-db
          property: connectionString
      - key: REDIS_URL
        value: # Add your Upstash Redis URL here

databases:
  - name: spotify-mood-db
    databaseName: spotify_mood
    user: spotify_user
    plan: free 