services:
  - type: web
    name: spotify-mood-backend
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install --prefer-binary -r backend/requirements.txt"
    startCommand: "cd backend && python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: SPOTIFY_CLIENT_ID
        sync: false  # Set in Render dashboard
      - key: SPOTIFY_CLIENT_SECRET
        sync: false  # Set in Render dashboard
      - key: GENIUS_ACCESS_TOKEN
        sync: false  # Set in Render dashboard
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: spotify-mood-db
          property: connectionString
      - key: REDIS_URL
        sync: false  # Set in Render dashboard

databases:
  - name: spotify-mood-db
    databaseName: spotify_mood
    user: spotify_user
    plan: free 